class for readme length in words
Joedahms/Software-Engineering-Project pull request #87
Opened 2024-09-23 13:01 UTC by dja1443

2024-09-23 16:05 UTC, Joedahms requested changes
See comments.

2024-09-23 16:05 UTC, Joedahms commented on src/metric.ts
> -  // Calculate RampUp
Delete all this commented out code.

2024-09-23 16:05 UTC, Joedahms commented on src/metric.ts
> +  //private octokit: Octokit; // Octokit object for API access
Delete this

2024-09-23 16:05 UTC, Joedahms commented on src/metric.ts
> +    //this.octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
Delete this

2024-09-23 16:05 UTC, Joedahms commented on src/metric.ts
> +
This should be a function in api_access.ts. I'm aiming to make all API calls in api_access.ts, keeping them out of metric.ts. Metric.ts is just for calculating the actual metrics. When you move it to api_access.ts, see if you can change it from a class to function.

2024-09-25 02:40 UTC, dja1443 reviewed
Done

2024-09-25 03:34 UTC, closed without merging